# Generated by Django 5.2.11 on 2026-03-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0006_remove_useridentity_svg_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('requirements', models.JSONField(default=dict)),
                ('rewards', models.JSONField(default=dict)),
                ('npc_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('map_id', models.CharField(default='overworld', max_length=64)),
                ('tile_x', models.IntegerField(default=10)),
                ('tile_y', models.IntegerField(default=10)),
                ('tutorial_step', models.IntegerField(default=0)),
                ('has_website', models.BooleanField(default=False)),
                ('neocities_username', models.CharField(blank=True, max_length=128)),
                ('links_harvested', models.IntegerField(default=0)),
                ('seeds_planted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to='plants.useridentity')),
            ],
        ),
        migrations.CreateModel(
            name='GardenPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_x', models.IntegerField()),
                ('slot_y', models.IntegerField()),
                ('link_url', models.URLField(blank=True)),
                ('link_title', models.CharField(blank=True, max_length=256)),
                ('plant_type', models.CharField(blank=True, max_length=64)),
                ('growth_stage', models.IntegerField(default=0)),
                ('planted_at', models.DateTimeField(blank=True, null=True)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plots', to='game.gameprofile')),
            ],
            options={
                'unique_together': {('profile', 'slot_x', 'slot_y')},
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_data', models.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to='game.gameprofile')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
            ],
            options={
                'unique_together': {('profile', 'quest')},
            },
        ),
    ]
