# Generated by Django 5.2.11 on 2026-03-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_seed_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenplot',
            name='link_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
