# Generated by Django 5.2.11 on 2026-03-13 15:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_game_profile_defaults(apps, schema_editor):
    GameProfile = apps.get_model('game', 'GameProfile')
    for profile in GameProfile.objects.select_related('identity').all():
        if not profile.garden_name:
            identity = profile.identity
            base = (identity.display_name or identity.username or "Gardner").strip()
            if not base:
                garden_name = "My Gardn"
            elif "gardn" in base.lower():
                garden_name = base[:80]
            else:
                garden_name = f"{base}'s Gardn"[:80]
            profile.garden_name = garden_name
            profile.save(update_fields=["garden_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gardenvisit'),
        ('plants', '0006_remove_useridentity_svg_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='appearance_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='body_style',
            field=models.CharField(choices=[('feminine', 'Feminine'), ('androgynous', 'Androgynous'), ('masculine', 'Masculine')], default='androgynous', max_length=32),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='fence_style',
            field=models.CharField(default='split_rail', max_length=32),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='garden_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='gate_state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='homestead_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='outfit_key',
            field=models.CharField(default='starter', max_length=32),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='path_style',
            field=models.CharField(default='stone', max_length=32),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='read_later_tag',
            field=models.CharField(default='read-later', max_length=64),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='skin_tone',
            field=models.CharField(default='olive', max_length=32),
        ),
        migrations.CreateModel(
            name='GroveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('is_moderated', models.BooleanField(default=False)),
                ('moderated_reason', models.CharField(blank=True, max_length=120)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grove_messages', to='plants.useridentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrovePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_map', models.CharField(default='neighbors', max_length=32)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grove_presence', to='plants.useridentity')),
            ],
        ),
        migrations.CreateModel(
            name='GardenDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(choices=[('north_west', 'Northwest'), ('north_east', 'Northeast'), ('south_west', 'Southwest'), ('south_east', 'Southeast'), ('signpost', 'Signpost')], max_length=32)),
                ('decor_key', models.CharField(max_length=32)),
                ('variant_key', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='game.gameprofile')),
            ],
            options={
                'ordering': ['slot_key'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'slot_key'), name='game_unique_garden_decoration_slot')],
            },
        ),
        migrations.RunPython(backfill_game_profile_defaults, migrations.RunPython.noop),
    ]
