# Generated by Django 5.2.11 on 2026-02-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
