# Generated by Django 5.2.11 on 2026-02-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_useridentity_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='show_harvests_on_profile',
            field=models.BooleanField(default=False),
        ),
    ]
