# Generated by Django 5.2.11 on 2026-02-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_useridentity_mastodon_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='animate_plant_motion',
            field=models.BooleanField(default=False),
        ),
    ]
