# Generated by Django 5.2.11 on 2026-03-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_useridentity_animate_plant_motion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentity',
            name='svg_cache',
        ),
    ]
