# Generated by Django 5.2.11 on 2026-03-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0003_harvest_mastodon_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
